theme = "rose_pine"

[editor]
line-number = "relative"
color-modes = true
auto-save = true
bufferline = "multiple"
scrolloff = 8

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "block"

[editor.lsp]
display-signature-help-docs = false
# display-inlay-hints = true


[keys.normal]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.insert]
C-c = "normal_mode"
